name: deeputi
channels:
  - conda-forge
dependencies:
  - python=3.10.4
  - tensorboard>=2.11.0
  - tensorflow-gpu>=2.11.0
  - scikit-image>=0.18.1
  - tqdm>=4.64.0
  - scipy>=1.8.0
  - seaborn>=0.11.2
  - scikit-learn>=1.0.2
  - neptune-client>=0.16.1
  - neptune-tensorflow-keras>=0.9.9
  - matplotlib
